### PR TITLE
Update Monster Encounter Tool.au3 w/ fix to premade encounter loading

### PR DESCRIPTION
**Pull request by Loneblackfang**
Fixed issue with loading in premade monster lists

### CODE REVIEW

**Comment by sdoddler** [comment]
Thanks Mate, I haven't worked for this project for a long time 👍

**Comment by Loneblackfang** [comment]
Im willing to help you out with this and help you maintain it

**Comment by sdoddler** [comment]
Have added you as a contributor - does that mean you can merge  whenever you like?

That way I dont need to approve anything that you want to add/fix :)

**Comment by Loneblackfang** [comment]
I checked but need to have premissions to merge or push to the main project

**Pull request merged**
